import { TopologyBlueprint, TopologyNodeTemplate, TopologyTemplateRule } from './types';

export const BUILTIN_NODE_TEMPLATES: TopologyNodeTemplate[] = [
  {
    id: 'router',
    name: 'Router',
    icon: 'router',
    fields: ['name', 'ip', 'traffic'],
  },
  {
    id: 'core-router',
    name: 'Core Router',
    icon: 'router',
    fields: ['name', 'ip', 'traffic', 'bgp'],
  },
  {
    id: 'olt',
    name: 'OLT',
    icon: 'olt',
    fields: ['name', 'ip', 'onuCount'],
  },
  {
    id: 'switch',
    name: 'Switch',
    icon: 'switch_managed',
    fields: ['name', 'ip'],
  },
  {
    id: 'server',
    name: 'Servidor',
    icon: 'server',
    fields: ['name', 'ip', 'cpu', 'memory'],
  },
  {
    id: 'generic',
    name: 'Genérico',
    fields: ['name', 'ip'],
  },
];

export const BUILTIN_TEMPLATE_RULES: TopologyTemplateRule[] = [
  {
    id: 'rule-olt-group',
    name: 'Grupo OLT',
    templateId: 'olt',
    condition: 'hostGroupContains',
    value: 'OLT',
    priority: 10,
  },
  {
    id: 'rule-core-ne8000',
    name: 'NE8000',
    templateId: 'core-router',
    condition: 'hostnameContains',
    value: 'NE8000',
    priority: 5,
  },
  {
    id: 'rule-router-tag',
    name: 'Tag router',
    templateId: 'router',
    condition: 'tagEquals',
    value: 'device_type=router',
    priority: 20,
  },
  {
    id: 'rule-switch-group',
    name: 'Grupo Switch',
    templateId: 'switch',
    condition: 'hostGroupContains',
    value: 'SW',
    priority: 30,
  },
  {
    id: 'rule-server-group',
    name: 'Grupo Servidor',
    templateId: 'server',
    condition: 'hostGroupContains',
    value: 'SERVER',
    priority: 40,
  },
];

export const BUILTIN_TOPOLOGY_BLUEPRINTS: TopologyBlueprint[] = [
  {
    id: 'pop-standard',
    name: 'POP padrão',
    description: 'CORE → SWITCH → duas OLTs dentro de uma rede POP.',
    networkBox: { label: 'POP', x: 60, y: 60, width: 520, height: 360 },
    roles: [
      {
        role: 'core',
        label: 'CORE',
        type: 'host',
        icon: 'router',
        nodeTemplateId: 'core-router',
        x: 260,
        y: 110,
      },
      {
        role: 'switch',
        label: 'SW',
        type: 'host',
        icon: 'switch_managed',
        nodeTemplateId: 'switch',
        x: 260,
        y: 200,
      },
      {
        role: 'olt1',
        label: 'OLT 1',
        type: 'host',
        icon: 'olt',
        nodeTemplateId: 'olt',
        x: 150,
        y: 290,
      },
      {
        role: 'olt2',
        label: 'OLT 2',
        type: 'host',
        icon: 'olt',
        nodeTemplateId: 'olt',
        x: 370,
        y: 290,
      },
    ],
    links: [
      { fromRole: 'core', toRole: 'switch' },
      { fromRole: 'switch', toRole: 'olt1' },
      { fromRole: 'switch', toRole: 'olt2' },
    ],
  },
  {
    id: 'backbone-simple',
    name: 'Backbone simples',
    description: 'Dois roteadores core ligados em anel.',
    roles: [
      {
        role: 'core-a',
        label: 'CORE A',
        type: 'host',
        icon: 'router',
        nodeTemplateId: 'core-router',
        x: 180,
        y: 200,
      },
      {
        role: 'core-b',
        label: 'CORE B',
        type: 'host',
        icon: 'router',
        nodeTemplateId: 'core-router',
        x: 420,
        y: 200,
      },
    ],
    links: [{ fromRole: 'core-a', toRole: 'core-b', medium: 'fiber' }],
  },
  {
    id: 'ftth-access',
    name: 'FTTH acesso',
    description: 'OLT com duas ONUs de acesso (hosts manuais).',
    networkBox: { label: 'FTTH', x: 80, y: 80, width: 400, height: 300 },
    roles: [
      {
        role: 'olt',
        label: 'OLT',
        type: 'host',
        icon: 'olt',
        nodeTemplateId: 'olt',
        x: 260,
        y: 140,
      },
      {
        role: 'onu1',
        label: 'ONU 1',
        type: 'host',
        icon: 'onu',
        x: 160,
        y: 260,
      },
      {
        role: 'onu2',
        label: 'ONU 2',
        type: 'host',
        icon: 'onu',
        x: 360,
        y: 260,
      },
    ],
    links: [
      { fromRole: 'olt', toRole: 'onu1', medium: 'fiber' },
      { fromRole: 'olt', toRole: 'onu2', medium: 'fiber' },
    ],
  },
];
